Repository ucdavis/ipa-web, pull requests merged in 2018-04, with the labels that each got.

#228 Adjustments to allow tasks to run in development
  .gitignore
  src/main/java/edu/ucdavis/dss/dw/DwClient.java
  src/main/java/edu/ucdavis/dss/dw/dto/DwCourse.java
  src/main/java/edu/ucdavis/dss/ipa/api/components/assignment/AssignmentViewTeachingAssignmentController.java
  src/main/java/edu/ucdavis/dss/ipa/api/components/course/CourseViewController.java
  src/main/java/edu/ucdavis/dss/ipa/entities/Course.java
  src/main/java/edu/ucdavis/dss/ipa/repositories/CourseRepository.java
  src/main/java/edu/ucdavis/dss/ipa/repositories/DataWarehouseRepository.java
  src/main/java/edu/ucdavis/dss/ipa/repositories/RestDataWarehouseRepository.java
  src/main/java/edu/ucdavis/dss/ipa/services/CourseService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaCourseService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaScheduleOpsService.java
  src/main/java/edu/ucdavis/dss/ipa/tasks/EmailNotificationTask.java
  src/main/java/edu/ucdavis/dss/ipa/tasks/TermUpdateTask.java
  src/main/java/edu/ucdavis/dss/ipa/tasks/UpdateCourseTask.java
  src/main/java/edu/ucdavis/dss/ipa/tasks/UpdateSectionsTask.java
  src/main/java/edu/ucdavis/dss/ipa/tasks/UpdateUsersTask.java
  src/main/resources/logback.xml
  src/test/java/edu/ucdavis/dss/ipa/repositories/MockDataWarehouseRepository.java
Labels: enhancement

#230 Correct selective unit sync logic
  src/main/java/edu/ucdavis/dss/ipa/repositories/CourseRepository.java
  src/main/java/edu/ucdavis/dss/ipa/repositories/ScheduleRepository.java
  src/main/java/edu/ucdavis/dss/ipa/services/CourseService.java
  src/main/java/edu/ucdavis/dss/ipa/services/ScheduleService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaCourseService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaScheduleService.java
  src/main/java/edu/ucdavis/dss/ipa/tasks/UpdateCourseTask.java
Labels: enhancement

#231 Guard against null instructor reference found in production
  src/main/java/edu/ucdavis/dss/ipa/api/components/assignment/AssignmentViewTeachingAssignmentController.java
Labels: bug

#232 Bugfix/correctly show instructor summary
  src/main/java/edu/ucdavis/dss/ipa/api/components/assignment/AssignmentViewController.java
  src/main/java/edu/ucdavis/dss/ipa/api/components/assignment/AssignmentViewSectionGroupController.java
  src/main/java/edu/ucdavis/dss/ipa/api/components/assignment/AssignmentViewTeachingAssignmentController.java
  src/main/java/edu/ucdavis/dss/ipa/api/components/assignment/AssignmentViewTeachingCallResponseController.java
  src/main/java/edu/ucdavis/dss/ipa/api/components/registrarReconciliationReport/RegistrarReconciliationReportController.java
  src/main/java/edu/ucdavis/dss/ipa/api/views/WorkgroupUserRolesView.java
  src/main/java/edu/ucdavis/dss/ipa/entities/Budget.java
  src/main/java/edu/ucdavis/dss/ipa/entities/UserRole.java
  src/main/java/edu/ucdavis/dss/ipa/services/InstructorService.java
  src/main/java/edu/ucdavis/dss/ipa/services/UserRoleService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaBudgetService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaInstructorCostService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaInstructorService.java
  src/main/java/edu/ucdavis/dss/ipa/services/jpa/JpaUserRoleService.java
Labels: High Priority, bug
